pkgs:
  name:
    - httpd
  state: present
fwd_svc:
  name:
  port: 8080/tcp
  state: enabled
  perm: yes
  now: yes
storage:
  partitions:
    number: 1
    start: 1MiB
    end: 1000MiB
    device: /dev/sdb
    state: present
  volume_groups:
    name: apache-vg
    device: /dev/sdb1
  logical_volumes:
    name: www-lv
    size: 500M
    mount_path: /srv/www
    fs: xfs
apache:
  docroot: /srv/www/html
  http_port: 8080
